import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import api from '../api'

const empty = {title:'',description:'',category:'IT',priority:'medium'}
export default function TicketForm(){
 const {id}=useParams(), navigate=useNavigate(); const [form,setForm]=useState(empty),[errors,setErrors]=useState({}),[loading,setLoading]=useState(false),[initial,setInitial]=useState(!!id)
 useEffect(()=>{if(id) api.get(`/tickets/${id}`).then(r=>setForm({title:r.data.title,description:r.data.description,category:r.data.category,priority:r.data.priority})).catch(()=>navigate('/tickets')).finally(()=>setInitial(false))},[id])
 const submit=async e=>{e.preventDefault();const x={};if(form.title.trim().length<4)x.title='Title must be at least 4 characters.';if(form.description.trim().length<10)x.description='Description must be at least 10 characters.';setErrors(x);if(Object.keys(x).length)return;try{setLoading(true);const r=id?await api.put(`/tickets/${id}`,form):await api.post('/tickets',form);navigate(`/tickets/${r.data.id}`)}catch(err){setErrors(err.response?.data?.errors||{general:'Could not save ticket.'})}finally{setLoading(false)}}
 if(initial)return <div className="page-center"><div className="spinner"/></div>
 return <div className="container page narrow"><div className="page-head"><div><span className="eyebrow">{id?'EDIT REQUEST':'NEW REQUEST'}</span><h1>{id?'Update ticket':'Report an issue'}</h1><p className="muted">Give enough detail so the issue can be understood quickly.</p></div></div><form className="panel form-card" onSubmit={submit}>{errors.general&&<div className="alert error">{errors.general}</div>}<label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Projector not working in Room 204"/>{errors.title&&<small className="field-error">{errors.title}</small>}</label><label>Description<textarea rows="6" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe what happened, where, and anything already tried..."/>{errors.description&&<small className="field-error">{errors.description}</small>}</label><div className="form-grid"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>IT</option><option>Facilities</option><option>Academic</option><option>Administration</option><option>Other</option></select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div><div className="form-actions"><button type="button" className="btn btn-ghost" onClick={()=>navigate(-1)}>Cancel</button><button className="btn btn-primary" disabled={loading}>{loading?'Saving...':id?'Save changes':'Create ticket'}</button></div></form></div>
}
